### ISSUE TITLE
[Web] El botón de compartir no funciona

### ISSUE THREAD

**Issue by alvarag** [dmlls/jizt#122]
**Describe el error:**
El botón de compartir (en web) no funciona y tampoco muestra ningún mensaje de que dicha funcionalidad no esté soportada.

**Pasos para reproduccir:**
Abrir un navegador (Firefox en mi caso):
1. Resumir cualquier texto.
2. Pulsar el botón de compartir del resumen generado.

**Resultados esperados:**
Entiendo que debería indicar que la funcionalidad no está todavía soportada o que abra una ventana con las opciones de compartir.

**Resultados obtenidos:**
Simplemente no hace nada.

**Información adicional:**
Esto ocurre en la versión web, se ha probado en Firefox y Chrome.

**Comment by dmlls** [comment]
Resuelto en https://github.com/dmlls/jizt-app/commit/2ecdd2a5631a96db955564403135f56393064940.

En la versión web, solo se muestra el botón de copiar.
