### ISSUE TITLE
Añadir en readme logo Ministerio

### ISSUE THREAD

**Issue by clopezno** [dmlls/jizt#40]
Añadir al final del Readme el logo del[ Ministerio de Educación y Formación Profesional](https://www.pap.hacienda.gob.es/bdnstrans/GE/es/convocatoria/714150/document/425421
) por la concesión de la Beca de colaboración con el Departamento de Ingeniería Informática de la UBU.

**Comment by clopezno** [comment]
Diego adjunta a esta issue la solicitud de propuesta de proyecto de firmada que se hizo y la resolución.

**Comment by dmlls** [comment]
[Beca Colaboración - Diego Miguel Lozano.pdf](https://github.com/dmlls/jizt/files/5519541/DiegoMiguelLozano-BecaColaboracion.pdf)
[Listado provisional firmado y publicado.pdf](https://github.com/dmlls/jizt/files/5519549/Resolucion_listado.provisional.firmado.y.publicado.pdf)
